defaults:
  - remote

MODEL:
  CLASSES: ["SPACE", "WALL_UNION_EX_OPENINGS", "RAILING_UNION", "WINDOW", "DOOR"]
  CROP_ENABLED: False
  RESIZE_ENABLED: True
  PAD_SIZE: 512
  MAX_SIZE: 512
SOLVER:
  NUM_WORKERS: 8
  BATCH_SIZE: 2
  EPOCHS: 5